package com.categorise.transactions.client;

import com.categorise.transactions.exception.ApplicationException;
import com.categorise.transactions.model.ClientResponse;
import com.categorise.transactions.model.Transaction;
import com.google.gson.Gson;

import java.util.List;

public class GetTransactionsClient {

  public List<Transaction> getTransactionsHardCoded() throws ApplicationException {
    try {
      Gson gson = new Gson();
      ClientResponse clientResponse =
          gson.fromJson(getTransactionsResponse(), ClientResponse.class);
      return clientResponse.getResults();
    } catch (Exception e) {
      throw new ApplicationException(e.getMessage());
    }
  }

  private String getTransactionsResponse() {
    return "{\n"
        + "  \"results\": [\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"0ef942ea-d3ad-4f25-857b-4d4bb7f912d8\",\n"
        + "      \"bookingDate\": \"2018-07-24\",\n"
        + "      \"description\": \"Starbucks Victoria Stn\",\n"
        + "      \"amount\": \"1000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"25a4d256-094f-4637-bea0-5f82760674b0\",\n"
        + "      \"bookingDate\": \"2017-04-28\",\n"
        + "      \"description\": \"INT'L 0020481195 AMAZON UK RETAIL A AMAZON.CO.UK\",\n"
        + "      \"amount\": \"23.12\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"2eeb4b27-eac8-4d6c-a1cb-18ad8c57514d\",\n"
        + "      \"bookingDate\": \"2017-09-02\",\n"
        + "      \"description\": \"TFL.GOV.UK/CP TFL TRAVEL CH\",\n"
        + "      \"amount\": \"4.69\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"4661c026-4605-4773-9b49-b781ed9909ca\",\n"
        + "      \"bookingDate\": \"2018-07-24\",\n"
        + "      \"description\": \"SAINSBURY'S\",\n"
        + "      \"amount\": \"2000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"4a503bc0-c7f5-4a5f-9ae7-7269ce9d951e\",\n"
        + "      \"bookingDate\": \"2017-11-07\",\n"
        + "      \"description\": \"INT'L 0020481195 AMAZON UK RETAIL A AMAZON.CO.UK\",\n"
        + "      \"amount\": \"46.99\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"transactionId\": \"5875d68d-d53c-4f4b-a447-1606059fe57f\",\n"
        + "      \"bookingDate\": \"2017-11-03\",\n"
        + "      \"description\": \"BT MOBILE\",\n"
        + "      \"amount\": \"34.6\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"58b87c57-b3e4-4b5b-9423-c0f13b9f2eb1\",\n"
        + "      \"bookingDate\": \"2018-07-22\",\n"
        + "      \"description\": \"CashPoint Angel\",\n"
        + "      \"amount\": \"850000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"698f1d0c-5b2b-449a-a668-c862c0aaef39\",\n"
        + "      \"bookingDate\": \"2017-12-16\",\n"
        + "      \"description\": \"LONDON TAXI JOURNE LONDON  E1\",\n"
        + "      \"amount\": \"6.51\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"73e752d3-e4a6-4bc5-b7ff-3d7b1f674404\",\n"
        + "      \"bookingDate\": \"2017-08-23\",\n"
        + "      \"description\": \"TOTAL CHARGES TO 05MAR2017\",\n"
        + "      \"amount\": \"4.12\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"75660071-9994-4457-93d8-002f6a080e17\",\n"
        + "      \"bookingDate\": \"2017-10-02\",\n"
        + "      \"description\": \"COSTA COFFEE\",\n"
        + "      \"amount\": \"6.2\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"8106907d-3e5f-4b90-be18-3e62df18a83c\",\n"
        + "      \"bookingDate\": \"2018-07-24\",\n"
        + "      \"description\": \"Starbuck Poultry Stn\",\n"
        + "      \"amount\": \"10000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"8439173b-4ef3-44c4-82fe-282bbae35dba\",\n"
        + "      \"bookingDate\": \"2017-04-02\",\n"
        + "      \"description\": \"Non-Sterling Transaction Fee\",\n"
        + "      \"amount\": \"29.33\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"8e4d2111-859c-49b1-8557-d5f52fdf6685\",\n"
        + "      \"bookingDate\": \"2018-01-13\",\n"
        + "      \"description\": \"Non-Sterling Transaction Fee\",\n"
        + "      \"amount\": \"20.55\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"9619d91f-954e-4aff-a89e-0a02dc71eff0\",\n"
        + "      \"bookingDate\": \"2018-07-25\",\n"
        + "      \"description\": \"qa test1\",\n"
        + "      \"amount\": \"2000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"a57a9f04-018d-4e23-8be1-15cd5a61ffc6\",\n"
        + "      \"bookingDate\": \"2017-06-16\",\n"
        + "      \"description\": \"BT MOBILE\",\n"
        + "      \"amount\": \"22.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"a5eb8fc9-c425-4e10-85a4-a937367206a9\",\n"
        + "      \"bookingDate\": \"2017-03-24\",\n"
        + "      \"description\": \"BT PLC\",\n"
        + "      \"amount\": \"247.67\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"afda4441-63bf-4e05-9a82-f6849e265ff2\",\n"
        + "      \"bookingDate\": \"2017-01-13\",\n"
        + "      \"description\": \"COSTA COFFEE\",\n"
        + "      \"amount\": \"13.9\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"b5420564-2f4e-4b10-bba9-274eab8d1b5f\",\n"
        + "      \"bookingDate\": \"2018-07-22\",\n"
        + "      \"description\": \"Starbucks Holborn Stn.\",\n"
        + "      \"amount\": \"15000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"bbf8df70-509b-405b-9206-9fc48d78ea20\",\n"
        + "      \"bookingDate\": \"2018-07-25\",\n"
        + "      \"description\": \"qa test2\",\n"
        + "      \"amount\": \"10000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"c98c9faa-c000-4efe-a5a4-9f09b65aa1ec\",\n"
        + "      \"bookingDate\": \"2018-03-03\",\n"
        + "      \"description\": \"BT MOBILE\",\n"
        + "      \"amount\": \"30.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"d0365c70-9695-4aab-be75-50de44a5b39f\",\n"
        + "      \"bookingDate\": \"2017-03-03\",\n"
        + "      \"description\": \"Non-Sterling Transaction Fee\",\n"
        + "      \"amount\": \"4.77\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"d6a43cff-de8b-473d-a00e-903c73b3c974\",\n"
        + "      \"bookingDate\": \"2018-03-20\",\n"
        + "      \"description\": \"PAYROLL LAURA TESTER\",\n"
        + "      \"amount\": \"6666.03\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"ee15ba88-6c8f-4b0c-92ad-d2cfbe660fcb\",\n"
        + "      \"bookingDate\": \"2018-07-22\",\n"
        + "      \"description\": \"LOSING MONEE\",\n"
        + "      \"amount\": \"6000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"ee2bd1a9-afcc-4878-a2d8-bc10414a5893\",\n"
        + "      \"bookingDate\": \"2018-01-02\",\n"
        + "      \"description\": \"INT'L 003243488 GITHUB.COM\",\n"
        + "      \"amount\": \"7230.1\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"eecc194c-ad83-45d7-8dfb-77f84d1721d2\",\n"
        + "      \"bookingDate\": \"2018-07-24\",\n"
        + "      \"description\": \"TEST MONEY MONEE\",\n"
        + "      \"amount\": \"6000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"f73921e2-8dd3-48fc-8096-cf7b8f10d5b7\",\n"
        + "      \"bookingDate\": \"2017-12-25\",\n"
        + "      \"description\": \"SENIOR DEBT INTEREST PMT\",\n"
        + "      \"amount\": \"1875.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"DEBIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"3dacfa8d-f627-4742-bdd2-0f3194fa9e91\",\n"
        + "      \"bookingDate\": \"2017-03-28\",\n"
        + "      \"description\": \"SOME DESIGN LIMITED\",\n"
        + "      \"amount\": \"750.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"41c30ff7-877b-45a1-ae2d-b996f0f7aebe\",\n"
        + "      \"bookingDate\": \"2017-09-24\",\n"
        + "      \"description\": \"SOME DESIGN LIMITED\",\n"
        + "      \"amount\": \"612.49\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"4f0784df-f91e-4e27-abd0-35ddb82f76eb\",\n"
        + "      \"bookingDate\": \"2017-10-28\",\n"
        + "      \"description\": \"LITTLE BUSINESS PLC\",\n"
        + "      \"amount\": \"112000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"50cfaae7-ffbb-4cc9-a858-513aa2bd743e\",\n"
        + "      \"bookingDate\": \"2018-07-22\",\n"
        + "      \"description\": \"BIG MONEEZ\",\n"
        + "      \"amount\": \"7500.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 6,\n"
        + "      \"transactionId\": \"73cace36-ef6d-4a7c-9541-73238d24eb6d\",\n"
        + "      \"bookingDate\": \"2018-07-25\",\n"
        + "      \"description\": \"qa test3\",\n"
        + "      \"amount\": \"6000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 4,\n"
        + "      \"transactionId\": \"baa36afb-6c82-4a52-ade1-b7e40f59146f\",\n"
        + "      \"bookingDate\": \"2018-07-24\",\n"
        + "      \"description\": \"Cash out HEATHROW\",\n"
        + "      \"amount\": \"6000.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    },\n"
        + "    {\n"
        + "      \"bankId\": 2,\n"
        + "      \"accountId\": \"fakeAcc62\",\n"
        + "      \"companyId\": 2,\n"
        + "      \"transactionId\": \"ea58e941-42b0-4e57-ad37-067be59bd0e5\",\n"
        + "      \"bookingDate\": \"2018-07-24\",\n"
        + "      \"description\": \"Nisa\",\n"
        + "      \"amount\": \"7500.0\",\n"
        + "      \"currencyCode\": \"GBP\",\n"
        + "      \"type\": \"CREDIT\"\n"
        + "    }\n"
        + "  ]\n"
        + "}";
  }
}
